### ISSUE TITLE
Delete Scan session on server

### ISSUE THREAD

**Issue by schousda** [fttx/barcode-to-pc-server#103]
Hello,
my server shows a scan session which does not exist in the phone app.
I can't delete it from the server.
Maybe add a delete button to the server list?

**Comment by fttx** [comment]
Hi, 

if you want to delete a scan session you have to do a swipe left over it.
![image](https://user-images.githubusercontent.com/5663423/36976223-1c7446d8-207d-11e8-9e5a-b050fbd549e5.png)
It will delete it also from the server as long it is connected.

At the moment there isn't a way to delete the scan sessions from the server through the user interface.
If you want to reset the server you have to delete the `%appdata%/barcode-to-pc-server` folder if you're using Windows, otherwise, if you're using macOS execute this command: `rm -rf "/Users/$(whoami)/Library/Application Support/barcode-to-pc-server"`

The fix on the server side will be included in the next version: https://github.com/fttx/barcode-to-pc-server/issues/75

**Comment by schousda** [comment]
Since the session is not shown in the app anymore, i have to clean the server.
Thanks.
