### ISSUE TITLE
How delete a scan session

### ISSUE THREAD

**Issue by traponto** [fttx/barcode-to-pc-server#92]
I did not understand if, and how, it is possible to delete a scan session. On the iPad app I understood that it is possible via the left-swipe action.

**Comment by fttx** [comment]
https://github.com/fttx/barcode-to-pc-server/issues/75

At the moment there isn't a way to delete the scan sessions from the server through the user interface.
If you want to reset the server you have to delete the %appdata%/barcode-to-pc-server folder if you're using Windows, otherwise, if you're using macOS execute this command: rm -rf "/Users/$(whoami)/Library/Application Support/barcode-to-pc-server"
